In [1]:
import numpy as np

**Problem 1**

In [2]:
np1 = np.diag([9,9,9])
print(np1)

[[9 0 0]
 [0 9 0]
 [0 0 9]]


**Problem 2**

In [6]:
np2 = np.arange(2, 33, 2).reshape(4, 4)
print(np2,"\n\n")
mean = np2.mean()
std = np2.std()

lower_bound = mean - 0.5 * std
upper_bound = mean + 0.5 * std

print(np2[(np2 >= lower_bound) & (np2 <= upper_bound)])

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]] 


[14 16 18 20]


**Problem 3**

In [8]:
np3 = np.zeros((9,9), dtype='int16')
print(np3)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


**Problem 4**

In [10]:
n = int(input("Enter a number: ")) # user input
cols = np.arange(1, n + 1)

np4 = np.ones((n, 1)) * cols 
print(np4.astype(int))

Enter a number:  3


[[1 2 3]
 [1 2 3]
 [1 2 3]]


**Problem 5**

In [15]:
n2 = int(input()) # user input but avoiding redunduncy in variables
np5 = list(map(int, input().split()))
p1_sum, p2_sum = 0,0
left, right = 0, n2-1
p1_turn = True

while left <= right:
    if np5[left] > np5[right]:  # Choose the larger card between the left and right
        card = np5[left]
        left += 1
    else:
        card = np5[right]
        right -= 1

    if p1_turn:  
        p1_sum += card
    else:  
        p2_sum += card
    
    p1_turn = not p1_turn  # Switch turns

# Output the final scores
print(f"{p1_sum} {p2_sum}")

 7
 1 2 3 4 5 6 7


16 12


**Problem 6**

In [34]:
n, m = map(int, input().split())
np6 = np.array([input().split() for _ in range(n)])

np6_shaped = np6.reshape(-1)

if any(el in ['C', 'M', 'Y'] for el in np6_shaped):
    print("#Color")
else:
    print("#Black&White")


# code works but gets runtime error, hope to get hint 

 2 2 
 C M
 Y Y 


(2, 2)
#Color
